# GitHub Actions Docs : https://docs.github.com/en/actions

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read # This is required for actions/checkout

env:
  CURRENT_BRANCH: ${{ github.ref_name }}

jobs:
  CI:
    if: contains(github.event.head_commit.message, 'deploy')
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Build code
        run: |
          echo "여기다가 빌드하기 추가"
          # Add your build steps here

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Debug SSH Connection
        run: |
          echo "Connecting to server shan8017.iptime.org as user jjpark57 with ps 501stclan?..."
          sshpass -p 501stclan? ssh -vvv -o StrictHostKeyChecking=no jjpark@shan8017.iptime.org "whoami"
        env:
          PASSWORD: 501stclan?