# GitHub Actions Docs : https://docs.github.com/en/actions

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read # This is required for actions/checkout

env:
  CURRENT_BRANCH: ${{ github.ref_name }}

jobs:
  CI:
    if: contains(github.event.head_commit.message, 'deploy')
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Build code
        run: |
          echo "여기다가 빌드하기 추가"
          # Add your build steps here

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # - name: Deploy to server
      #   env:
      #     SERVER_HOST: shan8017.iptime.org
      #     SERVER_USER: jjpark
      #     SERVER_DIR: /home/jjpark/Projects
      #     SSHPASS: ${{ secrets.SERVER_PASSWORD }}
      #   run: |
      #     # echo "Attempting to connect to server..."
      #     # sshpass -e ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "echo 'SSH connection successful'"
      #     echo "Copying files to the server..."
      #     sshpass -e scp -o StrictHostKeyChecking=no -r ./* $SERVER_USER@$SERVER_HOST:$SERVER_DIR
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          : shan8017.iptime.org
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: whoami

      # - name: Verify deployment
      #   env:
      #     SERVER_HOST: shan8017.iptime.org
      #     SERVER_USER: jjpark
      #     SSHPASS: ${{ secrets.SERVER_PASSWORD }}
      #   run: |
      #     echo "Verifying deployment..."
      #     sshpass -e ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "ls -l $SERVER_DIR"
